### ISSUE TITLE
app.min.js:1 Uncaught TypeError: Cannot read properties of null (reading 'insertBefore')     at Object.prepend (app.min.js:1:27962)     at Object.createNode (app.min.js:1:27350)     at ShareView.ShareView.savetheImage (app.min.js:1:39913)     at HTMLImageElement.n (app.min.js:1:34959)

### ISSUE THREAD

**Issue by crazysoft360247** [ninesystems/Virtual-tryon#14]
when i click same or facebook share or tweeter

**Comment by ninesys** [comment]
Facebook & tweeter sharing has been removed form the application in the newer version, As social media sharing is an deprecated feature
